uStudioTeam/brix-ui

packages/ui-website/pages/components/grid.tsx
=> Merge Grid breakpoint props

packages/ui-website/pages/components/badge.tsx, packages/ui-website/pages/components/checkbox.tsx, packages/ui-website/pages/components/drawer.tsx, packages/ui-website/pages/components/dropdown.tsx, packages/ui-website/pages/components/editable-text.tsx, packages/ui-website/pages/components/file-input.tsx, packages/ui-website/pages/components/meta.tsx, packages/ui-website/pages/components/modal.tsx, packages/ui-website/pages/components/multiple-select.tsx, packages/ui-website/pages/components/radio-group.tsx, packages/ui-website/pages/components/single-select.tsx, packages/ui-website/pages/components/slider.tsx, packages/ui-website/pages/components/switch.tsx, packages/ui-website/pages/components/tooltip.tsx, packages/ui/src/components/Checkbox/index.jsx, packages/ui/src/components/Checkbox/styles/index.js, packages/ui/src/components/Input/FileInput/index.d.ts, packages/ui/src/components/Input/FileInput/index.jsx, packages/ui/src/components/RadioGroup/index.d.ts, packages/ui/src/components/RadioGroup/styles/index.js, packages/ui/src/components/Select/styles/index.js, packages/ui/src/components/Select/types.d.ts, packages/ui/src/components/Slider/index.d.ts, packages/ui/src/components/Switch/index.d.ts, packages/ui/src/components/Switch/index.jsx, packages/ui/src/components/Switch/styles/index.js, packages/ui/src/components/Tooltip/index.d.ts, packages/ui/src/components/Tooltip/index.jsx
Resolves #37.
Fixes #30, fixes #31, fixes #32, fixes #38, fixes #41, fixes #42, fixes #48, fixes #57, fixes #60, fixes #61, fixes #62, fixes #66.
=> fix: rename Container styled-components, fix classNames props

packages/ui-website/pages/components/meta.tsx
=> feat(Meta, Website): Add target="_blank" to link in code example

packages/ui-website/pages/components/badge.tsx, packages/ui-website/pages/components/placeholder.tsx, packages/ui-website/pages/components/spinner.tsx, packages/ui-website/pages/components/tag.tsx, packages/ui/src/components/Badge/styles/inject.js, packages/ui/src/components/Tag/styles/inject.js
=> Add default values for style props

packages/ui/src/components/Button/index.jsx, packages/ui/src/components/Button/styles/inject.js
=> fix(Button): Fix Button styles

packages/ui-website/pages/components/dropdown.tsx, packages/ui/src/components/Dropdown/index.d.ts, packages/ui/src/components/Dropdown/index.jsx
=> fix(Dropdown): Fix PropTypes

packages/ui/src/components/Tabs/styles/index.js, packages/ui/src/components/Tabs/styles/inject.js
=> fix(Tabs): Fix tab active cursor

packages/ui-website/pages/components/flex.tsx
=> fix(Flex, Website): Add default value for direction

packages/ui/src/components/Modal/styles/index.js
=> fix(Modal): Fix opening of modal

packages/ui-website/pages/components/slider.tsx
=> feat(Slider, Website): Decrease step size for slider example

packages/ui-website/pages/components/multiple-select.tsx
=> fix(Multiselect, Website): Made select example fullwidth

packages/ui/src/components/Input/TextArea/index.d.ts
=> fix(TextArea): Add type extending from HTMLTextAreaElement

packages/ui-website/pages/components/editable-text.tsx, packages/ui/src/components/EditableText/index.jsx
=> fix(EditableText, Website): Change value and onChange in props table

packages/ui-website/pages/components/grid.tsx
=> fix(Grid, Website) Update grid documentation

packages/ui-website/pages/components/radio-group.tsx, packages/ui/src/components/RadioGroup/styles/index.js
=> fix(RadioGroup, Website): Fix disabled styles, update docs

packages/ui/src/components/Select/styles/inject.js
=> fix(Select, MultipleSelect): Remove transition delay

packages/ui/src/components/Input/NumberInput/index.jsx
=> fix(NumberInput): Number input validation

packages/docs-website/package.json, packages/ustudio-ui/package.json, packages/ustudio-ui/src/components/Flex/styles/index.js, packages/ustudio-ui/src/components/Grid/Grid/index.d.ts, packages/ustudio-ui/src/components/Grid/Grid/index.jsx, packages/ustudio-ui/src/components/Grid/index.d.ts, packages/ustudio-ui/src/components/Grid/stories/index.stories.jsx, packages/ustudio-ui/src/components/Grid/styles/inject.js, packages/ustudio-ui/src/components/Grid/utils/index.js, packages/ustudio-ui/src/index.d.ts
Resolves #118.
Fixes #117, fixes #119.
=> hotfix: Fix Grid children type validation and maxWidth calculation, add full-width to Flex

packages/docs-website/components/markdown/renderers.tsx
=> Fix(Website): Fix target blank for internal links

packages/ustudio-ui/src/components/Progress/styles/index.js
=> fix(Progress): Replace progress element with div

packages/ustudio-ui/src/components/Button/index.jsx, packages/ustudio-ui/src/components/Button/styles/inject.js
=> Fix(Buttons): Fix button styles

CHANGELOG.md, packages/docs-website/package.json, packages/ustudio-ui/CHANGELOG.md, packages/ustudio-ui/package.json, packages/ustudio-ui/src/components/Dropdown/index.jsx, packages/ustudio-ui/src/components/Spinner/index.jsx
=> fix: 1.1.5

packages/ustudio-ui/src/components/Button/styles/button.styles.js
=> fix(Button): fix button disable mobile styles

packages/ustudio-ui/src/components/Flex/flex.component.jsx, packages/ustudio-ui/src/components/Flex/flex.types.d.ts, packages/ustudio-ui/src/components/Text/text.component.jsx
=> fix(Text, Flex): add html attribute

packages/docs-website/pages/components/flex.tsx
=> fix(Website): fix visible link on  mobile IOS

packages/docs-website/pages/components/meta.tsx
=> fix(Documentation): Fix Meta examples alignment on mobile

packages/ustudio-ui/src/components/Select/styles/select.styles.js
=> fix(Select): Fix MultiSelect value container height

packages/ustudio-ui/src/components/Tooltip/styles/tooltip.styles.js, packages/ustudio-ui/src/components/Tooltip/tooltip.component.jsx
=> fix(Tooltip): fix visible tooltip on  mobile device

packages/core/src/block/block.styles.ts, packages/core/src/divider/divider.component.tsx, packages/core/src/divider/divider.props.d.ts, packages/core/src/divider/divider.styles.ts, packages/core/tests/text.spec.tsx, packages/utils/src/functions/index.ts, packages/utils/src/functions/parse-indent.ts
=> Divider updates

packages/core/src/block/block.styles.ts, packages/core/src/button/button.mixin.ts, packages/core/src/button/button.styles.ts, packages/core/src/divider/divider.component.tsx, packages/core/src/divider/divider.props.d.ts, packages/core/src/divider/divider.styles.ts, packages/core/tests/button.spec.tsx, packages/core/tests/text.spec.tsx, packages/utils/src/functions/index.ts, packages/utils/src/functions/parse-indent.ts
=> Button updates
